### ISSUE TITLE
Can not leverage NewDialer function due to cql-proxy version conflict

### ISSUE THREAD

**Issue by StevenLacerda** [datastax/gocql-astra#11]
In the critical gocql-astra change, we introduced https://github.com/datastax/gocql-astra/pull/6/files:
```
func NewDialer(b *astra.Bundle, timeout time.Duration) (gocql.HostDialer, error) {
	return &dialer{
		bundle: b,
		timeout: timeout,
	}, nil
}
```
And this is the new function that we will leverage. To use it, I need to create an astra.Bundle instance, and that turns out to be the problem.

In cql-proxy v0.1.3, astra.Bundle is defined as
```
type Bundle struct {
	tlsConfig *tls.Config
	host   string
	port   int
}
```
As the fields are not exported, there is no way I can create an instance. It has a bunch of other constructors like LoadBundleZip but I don’t see how I can easily use them without having a zip file. Note that the entire purpose of our change is to avoid needing a secure bundle zip file.

In cql-proxy v0.1.4, the fields in astra.Bundle are exported, meaning that I can directly instantiate them. But as said above, using v0.1.4 will cause build errors due to two versions.

Thus, the new functionality cannot be used without updating to 0.1.4 cql-proxy in gocql-astra.

**Comment by absurdfarce** [comment]
@StevenLacerda I've merged the PR @joao-r-reis created above to update the cql-proxy version used by gocql-astra.  Please let us know if you hit any other problems!
