### ISSUE TITLE
Unable to connect to Astra DB 

### ISSUE THREAD

**Issue by srikrishnabh1** [datastax/gocql-astra#14]
I get this error 
2023/07/08 12:49:52 unable to connect session: gocql: unable to create session: unable to discover protocol version: gocql: no response to connection startup within timeout

When I use the example code.
./example --astra-token <token> --astra-database-id <db_id>

Machine config:
Mac: Apple M1 chip
go version: go version go1.20.5 darwin/arm64

**Comment by joao-r-reis** [comment]
Do you have an issue with gocql-astra itself? Your issue with the `example` code is probably related to the timeout configuration. It doesn't let you customize the connect timeout but increasing that timeout setting on `gocql` would probably fix that.

**Comment by joao-r-reis** [comment]
Since this is quite old I'm going to close it, we can reopen it later if needed.
